export const GET_FOODS_REQUEST = 'GET_FOODS_REQUEST';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAIL = 'GET_FOODS_FAIL';

export const GET_FOOD_REQUEST = 'GET_FOOD_REQUEST';
export const GET_FOOD_SUCCESS = 'GET_FOOD_SUCCESS';
export const GET_FOOD_FAIL = 'GET_FOOD_FAIL';

export const UPDATE_FOOD_REQUEST = 'UPDATE_FOOD_REQUEST';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_FAIL = 'UPDATE_FOOD_FAIL';
export const UPDATE_FOOD_RESET = 'UPDATE_FOOD_RESET';

export const DELETE_FOOD_REQUEST = 'DELETE_FOOD_REQUEST';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_FAIL = 'DELETE_FOOD_FAIL';
export const DELETE_FOOD_RESET = 'DELETE_FOOD_RESET';

export const CREATE_FOOD_REQUEST = 'CREATE_FOOD_REQUEST';
export const CREATE_FOOD_SUCCESS = 'CREATE_FOOD_SUCCESS';
export const CREATE_FOOD_FAIL = 'CREATE_FOOD_FAIL';
export const CREATE_FOOD_RESET = 'CREATE_FOOD_RESET';