export const GET_MENU_CATEGORIES_REQUEST = 'GET_MENU_CATEGORIES_REQUEST';
export const GET_MENU_CATEGORIES_SUCCESS = 'GET_MENU_CATEGORIES_SUCCESS';
export const GET_MENU_CATEGORIES_FAIL = 'GET_MENU_CATEGORIES_FAIL';

export const GET_MENU_FOODS_REQUEST = 'GET_MENU_FOODS_REQUEST';
export const GET_MENU_FOODS_SUCCESS = 'GET_MENU_FOODS_SUCCESS';
export const GET_MENU_FOODS_FAIL = 'GET_MENU_FOODS_FAIL';