export const GET_TAKEAWAY_ORDERS_REQUEST = 'GET_TAKEAWAY_ORDERS_REQUEST';
export const GET_TAKEAWAY_ORDERS_SUCCESS = 'GET_TAKEAWAY_ORDERS_SUCCESS';
export const GET_TAKEAWAY_ORDERS_FAIL = 'GET_TAKEAWAY_ORDERS_FAIL';

export const GET_PLACE_ORDERS_REQUEST = 'GET_PLACE_ORDERS_REQUEST';
export const GET_PLACE_ORDERS_SUCCESS = 'GET_PLACE_ORDERS_SUCCESS';
export const GET_PLACE_ORDERS_FAIL = 'GET_PLACE_ORDERS_FAIL';

export const GET_QUICK_ORDERS_REQUEST = 'GET_QUICK_ORDERS_REQUEST';
export const GET_QUICK_ORDERS_SUCCESS = 'GET_QUICK_ORDERS_SUCCESS';
export const GET_QUICK_ORDERS_FAIL = 'GET_QUICK_ORDERS_FAIL';

export const ADD_QUICK_ORDER_REQUEST = 'ADD_QUICK_ORDER_REQUEST';
export const ADD_QUICK_ORDER_SUCCESS = 'ADD_QUICK_ORDER_SUCCESS';
export const ADD_QUICK_ORDER_FAIL = 'ADD_QUICK_ORDER_FAIL';
export const ADD_QUICK_ORDER_RESET = 'ADD_QUICK_ORDER_RESET';