export const GET_TAKEAWAY_ORDERS_REQUEST = 'GET_TAKEAWAY_ORDERS_REQUEST';
export const GET_TAKEAWAY_ORDERS_SUCCESS = 'GET_TAKEAWAY_ORDERS_SUCCESS';
export const GET_TAKEAWAY_ORDERS_FAIL = 'GET_TAKEAWAY_ORDERS_FAIL';

export const GET_PLACE_ORDERS_REQUEST = 'GET_PLACE_ORDERS_REQUEST';
export const GET_PLACE_ORDERS_SUCCESS = 'GET_PLACE_ORDERS_SUCCESS';
export const GET_PLACE_ORDERS_FAIL = 'GET_PLACE_ORDERS_FAIL';

export const UPDATE_PLACE_ORDERS_REQUEST = 'UPDATE_PLACE_ORDERS_REQUEST';
export const UPDATE_PLACE_ORDERS_SUCCESS = 'UPDATE_PLACE_ORDERS_SUCCESS';
export const UPDATE_PLACE_ORDERS_FAIL = 'UPDATE_PLACE_ORDERS_FAIL';
export const UPDATE_PLACE_ORDERS_RESET = 'UPDATE_PLACE_ORDERS_FAIL_RESET';

export const UPDATE_TAKEAWAY_ORDERS_REQUEST = 'UPDATE_TAKEAWAY_ORDERS_REQUEST';
export const UPDATE_TAKEAWAY_ORDERS_SUCCESS = 'UPDATE_TAKEAWAY_ORDERS_SUCCESS';
export const UPDATE_TAKEAWAY_ORDERS_FAIL = 'UPDATE_TAKEAWAY_ORDERS_FAIL';
export const UPDATE_TAKEAWAY_ORDERS_RESET = 'UPDATE_TAKEAWAY_ORDERS_RESET';

export const GET_QUICK_ORDERS_REQUEST = 'GET_QUICK_ORDERS_REQUEST';
export const GET_QUICK_ORDERS_SUCCESS = 'GET_QUICK_ORDERS_SUCCESS';
export const GET_QUICK_ORDERS_FAIL = 'GET_QUICK_ORDERS_FAIL';
export const GET_QUICK_ORDERS_RESET = 'GET_QUICK_ORDERS_RESET';

export const ADD_QUICK_ORDER_REQUEST = 'ADD_QUICK_ORDER_REQUEST';
export const ADD_QUICK_ORDER_SUCCESS = 'ADD_QUICK_ORDER_SUCCESS';
export const ADD_QUICK_ORDER_FAIL = 'ADD_QUICK_ORDER_FAIL';
export const ADD_QUICK_ORDER_RESET = 'ADD_QUICK_ORDER_RESET';

export const UPDATE_QUICK_ORDER_REQUEST = 'UPDATE_QUICK_ORDER_REQUEST';
export const UPDATE_QUICK_ORDER_SUCCESS = 'UPDATE_QUICK_ORDER_SUCCESS';
export const UPDATE_QUICK_ORDER_FAIL = 'UPDATE_QUICK_ORDER_FAIL';
export const UPDATE_QUICK_ORDER_RESET = 'UPDATE_QUICK_ORDER_RESET';

export const RELEASE_QUICK_ORDER_REQUEST = 'RELEASE_QUICK_ORDER_REQUEST';
export const RELEASE_QUICK_ORDER_SUCCESS = 'RELEASE_QUICK_ORDER_SUCCESS';
export const RELEASE_QUICK_ORDER_FAIL = 'RELEASE_QUICK_ORDER_FAIL';
export const RELEASE_QUICK_ORDER_RESET = 'RELEASE_QUICK_ORDER_RESET';

export const CLOSE_QUICK_ORDER_REQUEST = 'CLOSE_QUICK_ORDER_REQUEST';
export const CLOSE_QUICK_ORDER_SUCCESS = 'CLOSE_QUICK_ORDER_SUCCESS';
export const CLOSE_QUICK_ORDER_FAIL = 'CLOSE_QUICK_ORDER_FAIL';
export const CLOSE_QUICK_ORDER_RESET = 'CLOSE_QUICK_ORDER_RESET';