export const USER_TOKEN_SUCCESS = 'USER_TOKEN_SUCCESS';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';


export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USERAGREEMENT_REQUEST = 'GET_USERAGREEMENT_REQUEST';
export const GET_USERAGREEMENT_SUCCESS = 'GET_USERAGREEMENT_SUCCESS';
export const GET_USERAGREEMENT_FAIL = 'GET_USERAGREEMENT_FAIL';

export const PUT_USERAGREEMENT_REQUEST = 'PUT_USERAGREEMENT_REQUEST';
export const PUT_USERAGREEMENT_SUCCESS = 'PUT_USERAGREEMENT_SUCCESS';
export const PUT_USERAGREEMENT_FAIL = 'PUT_USERAGREEMENT_FAIL';
export const PUT_USERAGREEMENT_RESET = 'PUT_USERAGREEMENT_RESET';